using ArtCommission.Application.ArtistStudio.Commands.UploadArtwork;
using ArtCommission.Application.ArtistStudio.Marketplace;
using ArtCommission.Application.ArtistStudio.Queries.ManageCreatorArtworks;
using ArtCommission.Application.ArtistStudio.Queries.GetCreatorRateCard;
using ArtCommission.Application.ArtistStudio.Queries;
using ArtCommission.Application.ArtistStudio.DTOs;
using ArtCommission.Domain.Entities.ArtistStudio;
using ArtCommission.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

await using var db = new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
var creator = new CreatorProfile { UserId = Guid.NewGuid(), DisplayName = "Creator", AvailableSlots = 2 };
var follower = Guid.NewGuid();
db.CreatorProfiles.Add(creator);
db.Follows.Add(new Follow { FollowerUserId = follower, CreatorProfileId = creator.Id });
foreach (var status in new[] { "Approved", "Pending", "Hidden", "Rejected" })
    db.Artworks.Add(new Artwork { CreatorProfileId = creator.Id, CreatorProfile = creator, Title = status, ImageUrl = "/image.png", ModerationStatus = status });
await db.SaveChangesAsync();
var checks = 0;
void Check(bool condition, string message) { if (!condition) throw new Exception(message); checks++; }
var marketplace = new MarketplaceQueryHandler(db);
var feed = await marketplace.Handle(new GetFollowingFeedQuery(follower), default);
Check(feed.Count == 1 && feed[0].ModerationStatus == "Approved", "Following must exclude unapproved artwork");
Check(feed[0].CreatorName == "Creator" && feed[0].AvailableSlots == 2, "Filter metadata must come from creator");
var owned = new GetCreatorArtworksQueryHandler(db);
Check((await owned.Handle(new(creator.UserId, null, null), default)).Count == 4, "Owner can manage all statuses");
Check((await owned.Handle(new(creator.UserId, "Pending", "Pending"), default)).Count == 1, "Search and status combine");
var validator = new UploadArtworkCommandValidator();
Check(!validator.Validate(new UploadArtworkCommand(creator.UserId, "Test", null, "data:image/png;base64,abc", null)).IsValid, "Reject data URLs before database");
Check(!validator.Validate(new UploadArtworkCommand(creator.UserId, "Test", null, "/image.png", null, Tags: new[] { new string('a', 51) })).IsValid, "Tag must fit SQL column");
var upload = new UploadArtworkCommandHandler(db);
var result = await upload.Handle(new(creator.UserId, "Tags", null, "/image.png", null, Tags: new[] { " portrait ", "PORTRAIT" }), default);
Check(result.Success && await db.ArtworkTags.CountAsync(x => x.ArtworkId == result.Data!.Id) == 1, "Normalize tags before deduplication");
var approved = await db.Artworks.SingleAsync(x => x.Title == "Approved");
var editor = new UpdateCreatorArtworkCommandHandler(db);
Check((await editor.Handle(new(Guid.NewGuid(), approved.Id, "Hacked", null, null, null, null), default)).Data is null, "Other user cannot edit artwork");
Check((await editor.Handle(new(creator.UserId, approved.Id, "Updated", null, null, "/new.png", null), default)).Data?.ModerationStatus == "Pending", "Replacement image must be reviewed again");
Check((await marketplace.Handle(new GetFollowingFeedQuery(follower), default)).Count == 0, "Replaced image leaves public feed");
creator.RateCardJson = """[{"id":"portrait","name":"Portrait","price":350000,"milestones":[]}]""";
await db.SaveChangesAsync();
var rates = await new GetCreatorRateCardQueryHandler(db).Handle(new(creator.Id), default);
Check(rates.Success && rates.Data?.Count == 1, "Legacy package IDs must not erase rate card");
var order = new ArtCommission.Domain.Entities.Commission.Commission { CreatorId = creator.Id, ClientId = follower };
db.Commissions.Add(order);
db.Reviews.Add(new ArtCommission.Domain.Entities.Commission.Review { CommissionId = order.Id, Commission = order, ReviewerId = follower, Rating = 4 });
await db.SaveChangesAsync();
Check((await marketplace.Handle(new GetCreatorReviewsQuery(creator.Id), default)).Single().Rating == 4, "Completed-order reviews reach public profile");
Check((await CreatorRatingStats.LoadAsync(db, default))[creator.Id] == (4m, 1), "Ratings use actual review records");

var artworkForInteractions = new Artwork { CreatorProfileId = creator.Id, CreatorProfile = creator, Title = "Interactions", ImageUrl = "/interaction.png", ModerationStatus = "Approved" };
var album = new PersonalCollection { OwnerUserId = follower, Name = "Saved artwork" };
var otherUser = Guid.NewGuid();
db.Artworks.Add(artworkForInteractions);
db.PersonalCollections.Add(album);
await db.SaveChangesAsync();
var interactions = new ArtworkInteractionHandler(db);
var liked = await interactions.Handle(new SetArtworkLikeCommand(artworkForInteractions.Id, follower, true), default);
Check(liked is { IsLiked: true, LikeCount: 1 } && liked.CollectionIds.Count == 0, "Like is persistent and does not bookmark");
await interactions.Handle(new SetArtworkLikeCommand(artworkForInteractions.Id, follower, true), default);
Check(await db.ArtworkFavorites.CountAsync(f => f.ArtworkId == artworkForInteractions.Id) == 1, "Repeated like PUT is idempotent");
var saved = await interactions.Handle(new SetCollectionArtworkCommand(album.Id, artworkForInteractions.Id, follower, true), default);
Check(saved is { IsLiked: true } && saved.CollectionIds.Contains(album.Id), "Bookmark preserves independent like");
await interactions.Handle(new SetCollectionArtworkCommand(album.Id, artworkForInteractions.Id, follower, true), default);
Check(await db.CollectionArtworks.CountAsync(a => a.CollectionId == album.Id) == 1, "Repeated bookmark PUT is idempotent");
Check((await interactions.Handle(new GetCollectionArtworksQuery(album.Id, follower), default))?.Count == 1, "Saved artwork can be retrieved from owned album");
Check(await interactions.Handle(new GetCollectionArtworksQuery(album.Id, otherUser), default) is null, "Other user cannot read private collection");
Check(await interactions.Handle(new SetCollectionArtworkCommand(album.Id, artworkForInteractions.Id, otherUser, false), default) is null, "Other user cannot remove collection membership");
Check(await interactions.Handle(new SetCollectionArtworkCommand(album.Id, artworkForInteractions.Id, otherUser, true), default) is null, "Other user cannot add collection membership");
var unliked = await interactions.Handle(new SetArtworkLikeCommand(artworkForInteractions.Id, follower, false), default);
Check(unliked is { IsLiked: false, LikeCount: 0 } && unliked.CollectionIds.Contains(album.Id), "Unlike does not remove bookmark");
await interactions.Handle(new SetArtworkLikeCommand(artworkForInteractions.Id, follower, false), default);
var anonymous = await interactions.Handle(new GetArtworkInteractionsQuery(artworkForInteractions.Id, Guid.Empty), default);
Check(anonymous is { IsLiked: false } && anonymous.CollectionIds.Count == 0, "Anonymous read does not reveal memberships");
Check(await interactions.Handle(new SetArtworkLikeCommand(artworkForInteractions.Id, Guid.Empty, true), default) is null, "Anonymous like rejected");
Check(await interactions.Handle(new SetCollectionArtworkCommand(album.Id, artworkForInteractions.Id, Guid.Empty, true), default) is null, "Anonymous bookmark rejected");
await interactions.Handle(new SetArtworkLikeCommand(artworkForInteractions.Id, otherUser, true), default);
Check((await interactions.Handle(new GetArtworkInteractionsQuery(artworkForInteractions.Id, follower), default))?.LikeCount == 1, "Like count includes other users without changing current state");
var removed = await interactions.Handle(new SetCollectionArtworkCommand(album.Id, artworkForInteractions.Id, follower, false), default);
Check(removed is { IsLiked: false, LikeCount: 1 } && removed.CollectionIds.Count == 0, "Remove bookmark does not change anyone's like");
await interactions.Handle(new SetCollectionArtworkCommand(album.Id, artworkForInteractions.Id, follower, false), default);
Check((await interactions.Handle(new GetCollectionArtworksQuery(album.Id, follower), default))?.Count == 0, "Repeated remove is idempotent");
artworkForInteractions.ModerationStatus = "Hidden";
await db.SaveChangesAsync();
Check(await interactions.Handle(new SetArtworkLikeCommand(artworkForInteractions.Id, follower, true), default) is null, "Hidden artwork cannot be liked");
Check(await interactions.Handle(new SetCollectionArtworkCommand(album.Id, artworkForInteractions.Id, follower, true), default) is null, "Hidden artwork cannot be newly bookmarked");
album.IsDeleted = true;
await db.SaveChangesAsync();
Check(await interactions.Handle(new GetCollectionArtworksQuery(album.Id, follower), default) is null, "Deleted collection cannot be read");
var mutations = new MarketplaceMutationHandler(db);
Check(!(await mutations.Handle(new MarketplaceMutationCommand("comment", follower, Guid.NewGuid(), Text: "Test"), default)).Success, "Missing artwork comment rejected before FK failure");
Check(!(await mutations.Handle(new MarketplaceMutationCommand("comment", follower, artworkForInteractions.Id, Text: "Test"), default)).Success, "Hidden artwork comment rejected");
Check(!(await mutations.Handle(new MarketplaceMutationCommand("review", follower, creator.Id, Review: new CreateCreatorReviewRequest(5, "fake")), default)).Success, "Direct review cannot bypass completed commission checks");
var profileUpdate = new ArtCommission.Application.ArtistStudio.Commands.UpdateCreatorProfile.UpdateCreatorProfileCommand(
    creator.UserId, "Updated Creator", "", "", "", "", "", "", false, 0);
var profileValidator = new ArtCommission.Application.ArtistStudio.Commands.UpdateCreatorProfile.UpdateCreatorProfileCommandValidator();
Check(profileValidator.Validate(profileUpdate).IsValid, "Empty optional fields can be cleared");
foreach (var url in new[] { "javascript:alert(1)", "data:image/png;base64,abc", "not-a-url", "//example.com/banner.png" })
{
    Check(!profileValidator.Validate(profileUpdate with { WebsiteUrl = url }).IsValid, "Reject unsafe website URL");
    Check(!profileValidator.Validate(profileUpdate with { BannerUrl = url }).IsValid, "Reject invalid banner URL");
}
Check(profileValidator.Validate(profileUpdate with { WebsiteUrl = "https://example.com", BannerUrl = "https://example.com/banner.png" }).IsValid, "Accept HTTP(S) profile URLs");
Check(!profileValidator.Validate(profileUpdate with { Location = new string('x', 201) }).IsValid, "Location fits SQL limit");
Check(!profileValidator.Validate(profileUpdate with { WebsiteUrl = "https://example.com/" + new string('x', 500) }).IsValid, "Website fits SQL limit");
Check(!profileValidator.Validate(profileUpdate with { BannerUrl = "https://example.com/" + new string('x', 500) }).IsValid, "Banner fits SQL limit");
var profileEditor = new ArtCommission.Application.ArtistStudio.Commands.UpdateCreatorProfile.UpdateCreatorProfileCommandHandler(db);
Check(!(await profileEditor.Handle(profileUpdate with { UserId = Guid.NewGuid() }, default)).Success, "Another user cannot update this profile");
creator.Headline = "Old headline";
creator.WebsiteUrl = "https://example.com";
await db.SaveChangesAsync();
var editedProfile = await profileEditor.Handle(profileUpdate, default);
Check(editedProfile.Success && editedProfile.Data?.Id == creator.Id, "Editing preserves profile identity");
Check(creator.Headline is null && creator.WebsiteUrl is null && !creator.IsAcceptingOrders && creator.AvailableSlots == 0, "Editing clears fields and persists false/zero values");
var createValidator = new ArtCommission.Application.ArtistStudio.Commands.CreateCreatorProfile.CreateCreatorProfileCommandValidator();
Check(!createValidator.Validate(new ArtCommission.Application.ArtistStudio.Commands.CreateCreatorProfile.CreateCreatorProfileCommand(creator.UserId, "Creator", null, null, null, new string('x', 201), "javascript:alert(1)", "not-a-url")).IsValid, "Onboarding shares profile URL and length protections");
Console.WriteLine($"Passed {checks} creator feature checks.");
